const domElements = {
	stockFullData: document.getElementById("stockFullData"),
	cryptoFullData: document.getElementById("cryptoData"),
	symbolInput: document.getElementById("symbolInput"),
	searchStock: document.getElementById("searchStockBtn"),
	searchCrypto: document.getElementById("searchCryptoBtn"),
	lastUpdate: document.getElementById("lastUpdate"),
	refreshBtn: document.getElementById("refreshBtn"),
	marketCapEl: document.getElementById('marketCap'),
	priceUsdEl: document.getElementById('priceUsd'),
	change24hEl: document.getElementById('change24h'),
	volumeEl: document.getElementById('volume'),
	rankEl: document.getElementById('rank'),
	descriptionEl: document.getElementById('description'),
	lastUpdateEl: document.getElementById('lastUpdate'),
	symbolImageEl: document.getElementById('symbolImage'),
	circulatingSupplyEl: document.getElementById('circulatingSupply'),
	homepageLinkEl: document.getElementById('homepageLink'),
	symbolNameEl: document.getElementById('symbolName'),
	priceUsdTopEl: document.getElementById('priceUsdTop'),
	homepageTopEl: document.getElementById('homepageTop'),
	companyNameEl: document.getElementById('companyName'),
	companyExchangeEl: document.getElementById('companyExchange'),
	companyIndustryEl: document.getElementById('companyIndustry'),
	companyMarketCapEl: document.getElementById('companyMarketCap'),
	companyOutstandingEl: document.getElementById('companyOutstanding'),
	companyIpoEl: document.getElementById('companyIpo'),
	companyPhoneEl: document.getElementById('companyPhone'),
	companyWebUrlEl: document.getElementById('companyWebUrl'),
	companyTickerEl: document.getElementById('companyTicker'),
	companyCountryEl: document.getElementById('companyCountry'),
	companyCurrencyEl: document.getElementById('companyCurrency'),
};

export default domElements;
